# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-28 11:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': '\u0645\u0642\u0627\u0644\u0629', 'verbose_name_plural': '\u0645\u0642\u0627\u0644\u0627\u062a'},
        ),
        migrations.AddField(
            model_name='article',
            name='is_reviewed',
            field=models.BooleanField(default=False, verbose_name='\u0647\u0644 \u062a\u0645\u062a \u0627\u0644\u0645\u0631\u0627\u062c\u0639\u0629\u061f'),
        ),
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='\u062a\u0627\u0631\u064a\u062e \u0627\u0644\u0646\u0634\u0631'),
        ),
    ]
